param(
  [string]$PackagePath = ""
)

$ErrorActionPreference = "Stop"
$root = (Resolve-Path (Join-Path $PSScriptRoot "../..")).Path
Set-Location $root
$evidence = Join-Path $root ".phase56"
New-Item -ItemType Directory -Force -Path $evidence | Out-Null

$findings = [System.Collections.Generic.List[object]]::new()
$failures = [System.Collections.Generic.List[string]]::new()

function Add-Finding {
  param(
    [string]$Scope,
    [string]$Kind,
    [string]$Location,
    [string]$Classification
  )
  $findings.Add([ordered]@{
    scope = $Scope
    kind = $Kind
    location = $Location.Replace($root, "<repo>")
    classification = $Classification
  })
}

$publicFiles = @(
  git ls-files --cached --others --exclude-standard |
    Where-Object { $_ -and (Test-Path -LiteralPath $_ -PathType Leaf) }
)
$ignoredFiles = @(git ls-files --others --ignored --exclude-standard)
$forbiddenExtensions = '\.(sqlite3?|db|db-wal|db-shm|wav|mp3|m4a|aac|ogg|log|dmp|pfx|p12|pem|key|crt|cer|msix|appx|appxbundle)$'

foreach ($file in $publicFiles) {
  if ($file -match $forbiddenExtensions) {
    Add-Finding "working-tree" "forbidden-file" $file "unsafe"
    $failures.Add("Forbidden public file: $file")
  }
}

foreach ($file in $ignoredFiles) {
  if ($file -match $forbiddenExtensions -or
      $file -match '^(?i)(\.phase|e1\.md$|master_prompt|ephtodo-vault|vault[/\\]|vaults[/\\])') {
    Add-Finding "ignored-tree" "local-artifact" $file "unsafe-and-ignored"
  }
}

$patterns = [ordered]@{
  privateKey = '-----BEGIN (RSA |EC |OPENSSH )?PRIVATE KEY-----'
  cloudToken = '(AKIA[0-9A-Z]{16}|gh[oprsu]_[A-Za-z0-9]{30,}|sk-[A-Za-z0-9]{20,})'
  credentialAssignment = '(?i)(password|passwd|secret|access[_-]?token|private[_-]?key)\s*[:=]\s*["''][^"'']{8,}["'']'
  aiAttribution = '(?i)(generated by (cursor|chatgpt|openai|claude|anthropic|gemini|copilot)|co-authored-by:.*(cursor|openai|anthropic))'
  email = '[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}'
  windowsHome = '(?i)[A-Z]:\\Users\\[^\\\s"'']+'
  privateIp = '(?<![0-9])(10\.(?:[0-9]{1,3}\.){2}[0-9]{1,3}|192\.168\.(?:[0-9]{1,3}\.)[0-9]{1,3}|172\.(?:1[6-9]|2[0-9]|3[01])\.(?:[0-9]{1,3}\.)[0-9]{1,3})(?![0-9])'
}

foreach ($file in $publicFiles) {
  $item = Get-Item -LiteralPath $file
  if ($item.Length -gt 5MB) { continue }
  try {
    $content = [System.IO.File]::ReadAllText($item.FullName)
  } catch {
    continue
  }
  foreach ($entry in $patterns.GetEnumerator()) {
    if ($content -match $entry.Value) {
      $classification = switch ($entry.Key) {
        "credentialAssignment" {
          if ($file -like "test/*") {
            "fictional-test-data"
          } elseif ($file -eq "tooling/phase56/release_audit.ps1") {
            "required-public-source"
          } else {
            "unsafe"
          }
        }
        "aiAttribution" {
          if ($file -eq "tooling/phase56/release_audit.ps1") {
            "required-public-source"
          } else {
            "unsafe"
          }
        }
        "email" {
          if ($file -like "tooling/vendor/*" -or $file -eq "pubspec.lock") {
            "required-public-source"
          } else {
            "sanitized-documentation-or-fictional-test"
          }
        }
        "windowsHome" { "fictional-test-data" }
        "privateIp" { "sanitized-security-documentation" }
        default { "unsafe" }
      }
      Add-Finding "working-tree" $entry.Key $file $classification
      if ($classification -eq "unsafe") {
        $failures.Add("Unsafe $($entry.Key) pattern: $file")
      }
    }
  }
}

$historyText = git log --all --format=fuller -p --no-ext-diff
$historyMessages = git log --all --format="%B"
foreach ($entry in $patterns.GetEnumerator()) {
  if ($entry.Key -in @("windowsHome", "privateIp", "email", "credentialAssignment")) { continue }
  $historyScope = if ($entry.Key -eq "aiAttribution") {
    $historyMessages
  } else {
    $historyText
  }
  if (($historyScope -join "`n") -match $entry.Value) {
    Add-Finding "git-history" $entry.Key "<all-commits>" "unsafe"
    $failures.Add("Unsafe $($entry.Key) pattern in Git history")
  }
}

$identities = @(git log --all --format="%an|%cn" | Sort-Object -Unique)
foreach ($identity in $identities) {
  if ($identity -ne "devolopereph|devolopereph") {
    Add-Finding "git-history" "commit-identity" "<all-commits>" "unsafe"
    $failures.Add("Unexpected commit identity")
  }
}

$historyNames = @(git log --all --name-only --format="" | Where-Object { $_ })
foreach ($name in $historyNames) {
  if ($name -match $forbiddenExtensions) {
    Add-Finding "git-history" "forbidden-file" $name "unsafe"
    $failures.Add("Forbidden file in Git history: $name")
  }
}

$packageConfig = Get-Content ".dart_tool/package_config.json" -Raw | ConvertFrom-Json
$missingLicenses = [System.Collections.Generic.List[string]]::new()
foreach ($package in $packageConfig.packages) {
  if (-not $package.rootUri.StartsWith("file:")) { continue }
  $uri = [Uri]$package.rootUri
  $packageRoot = $uri.LocalPath
  $licenses = @(Get-ChildItem -LiteralPath $packageRoot -File -Filter "LICENSE*" -ErrorAction SilentlyContinue)
  if ($licenses.Count -eq 0) {
    if ($package.name -notin @("flutter_localizations", "flutter_test", "flutter_web_plugins")) {
      $missingLicenses.Add($package.name)
    }
  }
}
if ($missingLicenses.Count -gt 0) {
  Add-Finding "dependencies" "missing-license-file" ($missingLicenses -join ",") "requires-review"
}

if ($PackagePath) {
  $resolvedPackage = (Resolve-Path $PackagePath).Path
  Add-Type -AssemblyName System.IO.Compression.FileSystem
  $zip = [System.IO.Compression.ZipFile]::OpenRead($resolvedPackage)
  try {
    foreach ($entry in $zip.Entries) {
      if ($entry.FullName -match $forbiddenExtensions -or
          $entry.FullName -match '(?i)(vault\.json|\.phase|crash|test[/\\]|\.git)') {
        Add-Finding "package" "forbidden-content" $entry.FullName "unsafe"
        $failures.Add("Forbidden package content: $($entry.FullName)")
      }
    }
  } finally {
    $zip.Dispose()
  }
}

$result = [ordered]@{
  generatedAt = [DateTime]::UtcNow.ToString("o")
  publicFileCount = $publicFiles.Count
  ignoredFileCount = $ignoredFiles.Count
  commitCount = [int](git rev-list --all --count)
  remoteCount = @(git remote).Count
  dependencyPackageCount = $packageConfig.packages.Count
  missingLicenseFiles = @($missingLicenses)
  findings = @($findings)
  failures = @($failures | Sort-Object -Unique)
  passed = $failures.Count -eq 0
}
$reportPath = Join-Path $evidence "release-audit.json"
$result | ConvertTo-Json -Depth 8 | Set-Content -Encoding UTF8 $reportPath
Write-Output "RELEASE_AUDIT_REPORT=$reportPath"
Write-Output "RELEASE_AUDIT_FINDINGS=$($findings.Count)"
Write-Output "RELEASE_AUDIT_FAILURES=$($failures.Count)"
if ($failures.Count -gt 0) { exit 1 }
